language: python
python:
- '3.5'
install:
- pip install -r requirements-test.txt
script:
- echo `pwd` && PYTHONPATH="`pwd`:$PYTHONPATH" py.test --cov-report term-missing --cov-config=.coveragerc --cov=pymamba/
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack: iflexrtsstudio:DA5mI8cXzaRdkanMPINNpECW
env:
  global:
    secure: uuqSwqsJ0hZgbpH6y0WmnpHFMBVq8tZkCRip0THiUZevKLnGGEAjpkVue9Q3t7cIlcraGuihFzjLqzcEL6kuMlF7Q71MIXE5GtV74NhALf6CaS1TqrsmPxYI7rCtNudEqc8tst8uXwzhHEIBTSL7sp3kvkDPrXbPy+qCrm5bwLS7ORGw9XE9RzqryEPwfdqgYX9TTRJVogS5mPQyI8WsfvuJiGvIOaQYSev/RQxZIqktIsp0oXo0b5fA2JUcyXRWyk7FNsBydk2NJRAeKomc4ws1vMYP3ry5ebidTyPgijJRu0A06PvJRosOSA14PzxFphI7uxO7ix5aN/n1pQzUuuoJ3DuZwCYT8rmR3BQaWUDzHgAS1K9VuZopbkG79a/Q3b6M7CMZM170WtzTJyyptY4CS2yOwLLbeMl8ijiosPJHpYgm+M26WL93M3uDPEFlDfzhQ1nS1OqvPWUIYxswFcdyqpAitYUCrptDTfx78JC6VtxoVrsi2crfMhscPyeutDd1UyAxGVJFBedcTw4iLUZXwksbsx7USOxwDt965sXZbyAVzVSuXjF3ePVyblF1ZzTauO99oWMeSAS962SgqI/6WgBQco8hRsR/ylm3AR4Zu27CVDK9+BqZ288+lgslXWKVswR/SiMPQG/Ys1pfU8girz7AQ5iSCBr3vvvhKFU=
